CREATE TABLE user_card_collection_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id VARCHAR(255) NOT NULL,
    card_name VARCHAR(255) NOT NULL,
    card_name_normalized VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_user_card_collection_owner_card UNIQUE (owner_id, card_name_normalized),
    CONSTRAINT ck_user_card_collection_quantity CHECK (quantity > 0)
);

CREATE INDEX idx_user_card_collection_owner
    ON user_card_collection_items(owner_id);
