DELETE FROM deck_cards
WHERE deck_id IN (
    SELECT public_deck_id
    FROM meta_top_decks
    WHERE public_deck_id IS NOT NULL
);

DELETE FROM decks
WHERE id IN (
    SELECT public_deck_id
    FROM meta_top_decks
    WHERE public_deck_id IS NOT NULL
);

DROP TABLE IF EXISTS meta_top_deck_cards;
DROP TABLE IF EXISTS meta_top_decks;
DROP TABLE IF EXISTS meta_top_deck_import_batches;

CREATE TABLE IF NOT EXISTS meta_decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(32) NOT NULL,
    external_id VARCHAR(300) NOT NULL,
    commander VARCHAR(120) NOT NULL,
    commander_normalized VARCHAR(120) NOT NULL,
    color_identity VARCHAR(8),
    bracket VARCHAR(32) NOT NULL,
    event_name VARCHAR(300),
    event_date DATE,
    placement INTEGER,
    player_count INTEGER,
    url VARCHAR(1000),
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS meta_deck_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meta_deck_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_meta_deck_cards_deck FOREIGN KEY (meta_deck_id) REFERENCES meta_decks(id) ON DELETE CASCADE,
    CONSTRAINT ck_meta_deck_cards_quantity CHECK (quantity > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_meta_decks_source_external_id
    ON meta_decks(source, external_id);

CREATE INDEX IF NOT EXISTS ix_meta_decks_commander_bracket
    ON meta_decks(commander_normalized, bracket);

CREATE INDEX IF NOT EXISTS ix_meta_deck_cards_deck
    ON meta_deck_cards(meta_deck_id);
