CREATE TABLE IF NOT EXISTS decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    commander VARCHAR(255),
    owner_id VARCHAR(255),
    color_identity VARCHAR(255),
    CONSTRAINT pk_decks PRIMARY KEY (id),
    CONSTRAINT ck_decks_name_required CHECK (name IS NOT NULL AND btrim(name) <> ''),
    CONSTRAINT ck_decks_name_length CHECK (name IS NULL OR char_length(name) <= 120),
    CONSTRAINT ck_decks_commander_required CHECK (commander IS NOT NULL AND btrim(commander) <> ''),
    CONSTRAINT ck_decks_commander_length CHECK (commander IS NULL OR char_length(commander) <= 120),
    CONSTRAINT ck_decks_owner_id_required CHECK (owner_id IS NOT NULL AND btrim(owner_id) <> ''),
    CONSTRAINT ck_decks_color_identity_format CHECK (
        color_identity IS NULL
        OR color_identity = ''
        OR regexp_replace(color_identity, '[^A-Za-z]', '', 'g') ~ '^[WUBRGCwubrgc]*$'
    )
);

CREATE TABLE IF NOT EXISTS deck_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    quantity INTEGER NOT NULL,
    deck_id BIGINT,
    CONSTRAINT pk_deck_cards PRIMARY KEY (id),
    CONSTRAINT fk_deck_cards_deck_id FOREIGN KEY (deck_id) REFERENCES decks (id) ON DELETE CASCADE,
    CONSTRAINT ck_deck_cards_name_required CHECK (name IS NOT NULL AND btrim(name) <> ''),
    CONSTRAINT ck_deck_cards_name_length CHECK (name IS NULL OR char_length(name) <= 120),
    CONSTRAINT ck_deck_cards_quantity_range CHECK (quantity BETWEEN 1 AND 99)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_deck_cards_deck_id_name_ci
    ON deck_cards (deck_id, lower(name))
    WHERE deck_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_decks_owner_id
    ON decks (owner_id);

CREATE INDEX IF NOT EXISTS ix_decks_id_owner_id
    ON decks (id, owner_id);

CREATE INDEX IF NOT EXISTS ix_decks_commander_ci
    ON decks (lower(commander));

CREATE INDEX IF NOT EXISTS ix_deck_cards_deck_id
    ON deck_cards (deck_id);

CREATE INDEX IF NOT EXISTS ix_deck_cards_name_ci
    ON deck_cards (lower(name));

CREATE OR REPLACE FUNCTION fn_validate_deck_card_limits()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    affected_deck_id BIGINT;
    entry_count INTEGER;
    total_quantity INTEGER;
BEGIN
    IF TG_OP = 'DELETE' THEN
        affected_deck_id := OLD.deck_id;
    ELSE
        affected_deck_id := NEW.deck_id;
    END IF;

    IF affected_deck_id IS NULL THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;

    SELECT count(*), COALESCE(sum(quantity), 0)
      INTO entry_count, total_quantity
      FROM deck_cards
     WHERE deck_id = affected_deck_id;

    IF entry_count > 120 THEN
        RAISE EXCEPTION 'Deck % has % card entries; maximum is 120.', affected_deck_id, entry_count
            USING ERRCODE = '23514',
                  CONSTRAINT = 'ck_deck_cards_entries_per_deck';
    END IF;

    IF total_quantity > 99 THEN
        RAISE EXCEPTION 'Deck % has % cards; maximum main-deck size is 99.', affected_deck_id, total_quantity
            USING ERRCODE = '23514',
                  CONSTRAINT = 'ck_deck_cards_total_quantity_per_deck';
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_deck_cards_validate_limits ON deck_cards;

CREATE CONSTRAINT TRIGGER trg_deck_cards_validate_limits
AFTER INSERT OR UPDATE OR DELETE ON deck_cards
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION fn_validate_deck_card_limits();
