ALTER TABLE decks
    ADD COLUMN IF NOT EXISTS source_type VARCHAR(32);

ALTER TABLE decks
    ADD COLUMN IF NOT EXISTS external_source VARCHAR(255);

ALTER TABLE decks
    ADD COLUMN IF NOT EXISTS external_source_url VARCHAR(1000);

ALTER TABLE decks
    ADD COLUMN IF NOT EXISTS external_deck_url VARCHAR(1000);

ALTER TABLE decks
    ADD COLUMN IF NOT EXISTS external_rank INTEGER;

ALTER TABLE decks
    ADD COLUMN IF NOT EXISTS imported_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS deck_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id BIGINT NOT NULL,
    owner_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_deck_likes_deck FOREIGN KEY (deck_id) REFERENCES decks(id) ON DELETE CASCADE,
    CONSTRAINT uk_deck_likes_deck_owner UNIQUE (deck_id, owner_id)
);

CREATE INDEX IF NOT EXISTS ix_deck_likes_deck_created
    ON deck_likes (deck_id, created_at);

CREATE INDEX IF NOT EXISTS ix_deck_likes_owner
    ON deck_likes (owner_id);

CREATE INDEX IF NOT EXISTS ix_decks_external_source
    ON decks (source_type, external_source);
