CREATE TABLE IF NOT EXISTS meta_top_deck_import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(32) NOT NULL,
    ranking_period VARCHAR(32) NOT NULL,
    ranking_date DATE NOT NULL,
    status VARCHAR(32) NOT NULL,
    imported_decks INTEGER NOT NULL DEFAULT 0,
    created_decks INTEGER NOT NULL DEFAULT 0,
    updated_decks INTEGER NOT NULL DEFAULT 0,
    ignored_decks INTEGER NOT NULL DEFAULT 0,
    warnings_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS meta_top_decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(32) NOT NULL,
    source_url VARCHAR(1000),
    deck_url VARCHAR(1000),
    name VARCHAR(120) NOT NULL,
    format VARCHAR(32) NOT NULL,
    commander VARCHAR(120) NOT NULL,
    commander_normalized VARCHAR(120) NOT NULL,
    deck_rank INTEGER NOT NULL,
    ranking_period VARCHAR(32) NOT NULL,
    ranking_date DATE NOT NULL,
    archetype VARCHAR(32) NOT NULL,
    bracket VARCHAR(32) NOT NULL,
    color_identity VARCHAR(8),
    wins INTEGER,
    losses INTEGER,
    popularity_score DOUBLE PRECISION,
    public_deck_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_meta_top_decks_public_deck FOREIGN KEY (public_deck_id) REFERENCES decks(id) ON DELETE SET NULL,
    CONSTRAINT ck_meta_top_decks_rank_positive CHECK (deck_rank > 0),
    CONSTRAINT ck_meta_top_decks_format CHECK (format = 'COMMANDER'),
    CONSTRAINT ck_meta_top_decks_color_identity CHECK (
        color_identity IS NULL OR color_identity = '' OR color_identity ~ '^[WUBRG]*$'
    )
);

CREATE TABLE IF NOT EXISTS meta_top_deck_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    top_deck_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    name_normalized VARCHAR(120) NOT NULL,
    quantity INTEGER NOT NULL,
    section VARCHAR(32) NOT NULL,
    scryfall_id VARCHAR(80),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_meta_top_deck_cards_deck FOREIGN KEY (top_deck_id) REFERENCES meta_top_decks(id) ON DELETE CASCADE,
    CONSTRAINT ck_meta_top_deck_cards_quantity CHECK (quantity > 0),
    CONSTRAINT ck_meta_top_deck_cards_section CHECK (section IN ('MAIN', 'COMMANDER'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_meta_top_decks_url_snapshot
    ON meta_top_decks (source, ranking_period, ranking_date, lower(deck_url))
    WHERE deck_url IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_meta_top_decks_rank_snapshot
    ON meta_top_decks (source, ranking_period, ranking_date, format, commander_normalized, deck_rank);

CREATE INDEX IF NOT EXISTS ix_meta_top_decks_filters
    ON meta_top_decks (source, ranking_period, ranking_date, bracket, archetype);

CREATE INDEX IF NOT EXISTS ix_meta_top_decks_commander_bracket
    ON meta_top_decks (commander_normalized, bracket);

CREATE INDEX IF NOT EXISTS ix_meta_top_decks_public_deck
    ON meta_top_decks (public_deck_id);

CREATE INDEX IF NOT EXISTS ix_meta_top_deck_cards_deck
    ON meta_top_deck_cards (top_deck_id);

CREATE INDEX IF NOT EXISTS ix_meta_top_deck_cards_name
    ON meta_top_deck_cards (name_normalized);
