app.name=MTG Deck Manager API
app.version=0.0.0-local
app.commit=local
app.branch=local
app.buildTime=local
app.environment=local
app.creator=Danilo Catapan
app.objective=Analise e otimizacao de decks Commander com recomendacoes explicaveis.
